# https://taskfile.dev

version: "3"

tasks:
  check:
    desc: Check Python code.
    cmds:
      - ruff check --fix

  format:
    desc: Format Python code.
    cmds:
      - ruff format

  test:
    desc: Run tests
    cmds:
      - pytest
