name: Create release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git tag value'
        required: true
        type: string

env:
  PYTHON_VERSION: "3.12"
  GIT_MAIN_BRANCH: main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GIT_MAIN_BRANCH }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Set up Git user
        uses: fregante/setup-git-user@v2

      - name: Get release version
        id: version
        run: echo "VALUE=$(npx --yes semver ${{ github.event.inputs.tag }})" >> "$GITHUB_OUTPUT"

      - name: Update project version
        run: |
          uv version ${{ steps.version.outputs.VALUE }}
          git add pyproject.toml
          git commit -m "chore: release ${{ steps.version.outputs.VALUE }}"
          git push
          git tag ${{ steps.version.outputs.VALUE }}
          git push origin ${{ steps.version.outputs.VALUE }}
