name: Deploy to AWS Lambda

on:
  # This GH Action is no longer used as the web VocExcel app
  # is now part of the Tools web app.
  workflow_dispatch:

env:
  NODE_VERSION: "18"
  PYTHON_VERSION: "3.12"
  LAMBDA_FUNCTION_NAME: vocexcel
  PROJECT_NAME: "vocexcel"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: uv sync

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Package AWS Lambda artifact
        run: |
          (cd .venv/lib/python3.11/site-packages; zip ../../.././../lambda.zip -r .)
          zip -r lambda.zip -u lambda_function.py ${{env.PROJECT_NAME}}

      - name: Upload lambda artifact
        run: aws lambda update-function-code --function-name=${{ env.LAMBDA_FUNCTION_NAME }} --zip-file=fileb://lambda.zip
